linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gomnd
    - gomoddirectives
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nakedret
    - nestif
    - nonamedreturns
    - revive
    - stylecheck
    - varnamelen
    - wrapcheck
    - wsl
    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
